-- LIVRARIA

CREATE TABLE PUBLISHER (
  name VARCHAR(15) PRIMARY KEY,
  address VARCHAR(40),
  phone CHAR(11)  
);

CREATE TABLE BOOK (
  book_id VARCHAR(5) PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  publisher_name VARCHAR(20) NOT NULL UNIQUE
);


CREATE TABLE BOOK_AUTHORS (
  book_id VARCHAR(5) PRIMARY KEY,
  author_name VARCHAR(15) PRIMARY KEY
);

CREATE TABLE LIBRARY_BRANCH (
  branch_id VARCHAR(10) PRIMARY KEY,
  branch_name VARCHAR(15) NOT NULL,
  address VARCHAR(40)
);

CREATE TABLE BOOK_COPIES (
  book_id VARCHAR() PRIMARY KEY,
  branch_id VARCHAR() PRIMARY KEY,
  no_of_copies VARCHAR() NOT NULL
);

CREATE TABLE BOOK_LOANS (
  book_id VARCHAR() PRIMARY KEY,
  branch_id VARCHAR() PRIMARY KEY,
  card_no VARCHAR() PRIMARY KEY,
  date_out datetime NOT NULL,
  due_date datetime NOT NULL
);



CREATE TABLE LIBRARY_BRANCH (
  card_no VARCHAR() PRIMARY KEY,
  name VARCHAR() NOT NULL,
  address VARCHAR() NOT NULL UNIQUE,
  phone VARCHAR() UNIQUE
);

CREATE TABLE BORROWER (
  card_no VARCHAR() PRIMARY KEY,
  name VARCHAR() NOT NULL,
  address VARCHAR() NOT NULL UNIQUE,
  phone VARCHAR() UNIQUE
);